//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking()
        {
            this.CustomerSeatMaps = new HashSet<CustomerSeatMap>();
        }
    
        public int BookingId { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> BookingDateTime { get; set; }
        public string Status { get; set; }
        public Nullable<int> NoOfSeats { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<bool> Driver { get; set; }
    
        public bus bus { get; set; }
        public customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<CustomerSeatMap> CustomerSeatMaps { get; set; }
    }
}
