//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSeatMap
    {
        public int csmId { get; set; }
        public Nullable<int> customeId { get; set; }
        public Nullable<int> busId { get; set; }
        public Nullable<int> bookingId { get; set; }
        public System.DateTime boardingDate { get; set; }
        public Nullable<bool> S1 { get; set; }
        public Nullable<bool> S2 { get; set; }
        public Nullable<bool> S3 { get; set; }
        public Nullable<bool> S4 { get; set; }
        public Nullable<bool> S5 { get; set; }
        public Nullable<bool> S6 { get; set; }
        public Nullable<bool> S7 { get; set; }
        public Nullable<bool> S8 { get; set; }
        public Nullable<bool> S9 { get; set; }
        public Nullable<bool> S10 { get; set; }
        public Nullable<bool> S11 { get; set; }
        public Nullable<bool> S12 { get; set; }
        public Nullable<bool> S13 { get; set; }
        public Nullable<bool> S14 { get; set; }
        public Nullable<bool> S15 { get; set; }
        public Nullable<bool> S16 { get; set; }
        public Nullable<bool> S17 { get; set; }
        public Nullable<bool> S18 { get; set; }
        public Nullable<bool> S19 { get; set; }
        public Nullable<bool> S20 { get; set; }
        public Nullable<bool> S21 { get; set; }
        public Nullable<bool> S22 { get; set; }
        public Nullable<bool> S23 { get; set; }
        public Nullable<bool> S24 { get; set; }
    
        public booking booking { get; set; }
        public bus bus { get; set; }
        public customer customer { get; set; }
    }
}
